#!/bin/bash


# The sw_vers command will give you the current Mac operating system version and
# build number.
sw_vers
uname -a

# The system_profiler command is a command line interface (CLI) to the System
# Profiler application that every Mac comes with. This command is useful in
# situations where it is necessary to probe a machine that you don’t have
# permissions to access a GUI.

# This will generate a text report of information from System Profiler without 
# any personal or identifying information.
# system_profiler -detailLevel mini

# This command generates the report with only the basic hardware and network
# information.
# system_profiler -detailLevel basic

# Generates a report with all of the available information from System Profiler.
# system_profiler -detailLevel full

# The view a list of the types of data that are available, the -listDataTypes
# flag can be used.
# system_profiler -listDataTypes
system_profiler

# The report generated by system_profiler can be output to XML using the -xml
# flag.
# system_profiler -xml SPEthernetDataType SPFirewallDataType > ~/Documents/reports/system_profile-EthernetFirewall.xml
 